version: '3'
services:
  bitcoind_1:
    container_name: bitcoind_1
    build: .
    cap_add:
      - ALL
    command: bitcoind -regtest -server -txindex=0 -prune=0 -blockfilterindex -peerblockfilters -fallbackfee=0.0002 -rpcallowip=0.0.0.0/0 -rpcbind=0.0.0.0 -addnode=bitcoind_2:18444 -rpcuser=user -rpcpassword=pass --datadir=/opt/bitcoin
    ports:
        - 18444:18444
        - 18443:18443
    volumes:
      - bitcoind_1-regtest:/opt/bitcoin/regtest
  bitcoind_2:
    container_name: bitcoind_2
    build: .
    cap_add:
      - ALL
    command: bitcoind -regtest -server -txindex=0 -prune=0 -blockfilterindex -peerblockfilters -fallbackfee=0.0002 -rpcallowip=0.0.0.0/0 -rpcbind=0.0.0.0 -addnode=bitcoind_1:18444 -rpcuser=user -rpcpassword=pass --datadir=/opt/bitcoin
    ports:
      - 18555:18444
      - 18554:18443
    volumes:
      - bitcoind_2-regtest:/opt/bitcoin/regtest
volumes:
  bitcoind_1-regtest:
  bitcoind_2-regtest: